# --- REPOSITORY INFO ---
REPO_OWNER="R0Xofficial"
REPO_NAME="PlainUB-Extras"

# --- GLOBALL TIME SETTINGS ---
TINY_TIMEOUT=3
SMALL_TIMEOUT=5
MEDIUM_TIMEOUT=8
LONG_TIMEOUT=10
VERY_LONG_TIMEOUT=15
LARGE_TIMEOUT=30
